// League activity.
//
// The feed is what makes a private league feel alive between kickoffs, so
// entries are generated by the system rather than typed by anyone: results,
// week winners, streaks, upsets, eliminations.
//
// Every generated entry carries a dedup_key, and a partial unique index on
// (league_id, dedup_key) makes re-running the generator a no-op instead of a
// duplicate. That matters because grading runs every few minutes.

import type { SupabaseClient } from '@supabase/supabase-js';

export type ActivityType =
  | 'week_winner'
  | 'big_upset'
  | 'perfect_week'
  | 'streak'
  | 'survivor_out'
  | 'survivor_won'
  | 'joined'
  | 'milestone';

export interface ActivityEntry {
  leagueId: string;
  userId: string | null;
  activityType: ActivityType;
  message: string;
  season: number;
  week: number | null;
  dedupKey: string;
}

/** An upset worth talking about: a winning pick at this price or longer. */
const UPSET_ODDS = 250;

/** A streak only becomes news at this length, then every win after. */
const STREAK_FLOOR = 4;

export interface GenerateReport {
  created: number;
  warnings: string[];
}

/**
 * Write entries, ignoring any that already exist.
 *
 * Uses the dedup key rather than checking first, so two overlapping cron runs
 * cannot both decide an entry is missing and write it twice.
 */
export async function writeActivity(
  db: SupabaseClient,
  entries: readonly ActivityEntry[],
): Promise<GenerateReport> {
  const report: GenerateReport = { created: 0, warnings: [] };
  if (entries.length === 0) return report;

  const rows = entries.map((e) => ({
    league_id: e.leagueId,
    user_id: e.userId,
    activity_type: e.activityType,
    message: e.message,
    season: e.season,
    week: e.week,
    dedup_key: e.dedupKey,
  }));

  const { error, count } = await db
    .from('league_activity')
    .upsert(rows, { onConflict: 'league_id,dedup_key', ignoreDuplicates: true, count: 'exact' });

  if (error) {
    report.warnings.push(`activity write: ${error.message}`);
    return report;
  }

  report.created = count ?? 0;
  return report;
}

interface GradedPick {
  user_id: string;
  league_id: string;
  result: string;
  points: number;
  contest_odds: number | null;
  selection_label: string | null;
  market_type: string;
}

/**
 * Build the week's entries from what actually happened.
 *
 * Pure: takes rows, returns entries. The caller does the writing, so this can
 * be reasoned about and tested without a database.
 */
export function buildWeeklyActivity(input: {
  season: number;
  week: number;
  leagueId: string;
  standings: readonly { userId: string; username: string; totalPoints: number; rank: number; isWinner: boolean }[];
  picks: readonly GradedPick[];
  usernames: ReadonlyMap<string, string>;
}): ActivityEntry[] {
  const { season, week, leagueId, standings, picks, usernames } = input;
  const entries: ActivityEntry[] = [];
  const name = (id: string) => usernames.get(id) ?? 'Someone';

  for (const winner of standings.filter((s) => s.isWinner)) {
    entries.push({
      leagueId,
      userId: winner.userId,
      activityType: 'week_winner',
      message: `${winner.username} won week ${week} with ${winner.totalPoints} points`,
      season,
      week,
      dedupKey: `week_winner:${season}:${week}:${winner.userId}`,
    });
  }

  // Biggest upset of the week, once — not one entry per long shot.
  const upsets = picks
    .filter((p) => p.result === 'win' && (p.contest_odds ?? 0) >= UPSET_ODDS)
    .sort((a, b) => (b.contest_odds ?? 0) - (a.contest_odds ?? 0));

  const best = upsets[0];
  if (best) {
    entries.push({
      leagueId,
      userId: best.user_id,
      activityType: 'big_upset',
      message: `${name(best.user_id)} called ${best.selection_label ?? 'a long shot'} at +${best.contest_odds} for ${Math.round(best.points)} points`,
      season,
      week,
      dedupKey: `big_upset:${season}:${week}:${leagueId}`,
    });
  }

  // A perfect card, only when it is actually an achievement.
  const byUser = new Map<string, GradedPick[]>();
  for (const pick of picks) {
    byUser.set(pick.user_id, [...(byUser.get(pick.user_id) ?? []), pick]);
  }

  for (const [userId, userPicks] of byUser) {
    const settled = userPicks.filter((p) => p.result !== 'pending');
    if (settled.length >= 5 && settled.every((p) => p.result === 'win')) {
      entries.push({
        leagueId,
        userId,
        activityType: 'perfect_week',
        message: `${name(userId)} went ${settled.length} for ${settled.length} in week ${week}`,
        season,
        week,
        dedupKey: `perfect_week:${season}:${week}:${userId}`,
      });
    }
  }

  return entries;
}

export function buildStreakActivity(input: {
  season: number;
  week: number;
  leagueId: string;
  streaks: readonly { userId: string; username: string; streak: number }[];
}): ActivityEntry[] {
  return input.streaks
    .filter((s) => s.streak >= STREAK_FLOOR)
    .map((s) => ({
      leagueId: input.leagueId,
      userId: s.userId,
      activityType: 'streak' as const,
      message: `${s.username} is on a ${s.streak}-pick heater`,
      season: input.season,
      week: input.week,
      // Keyed on the streak length so each new rung is its own entry.
      dedupKey: `streak:${input.season}:${s.userId}:${s.streak}`,
    }));
}

export function buildSurvivorActivity(input: {
  season: number;
  week: number;
  leagueId: string;
  eliminated: readonly { userId: string; username: string; teamAbbr: string }[];
  winner: { userId: string; username: string } | null;
  poolName: string;
  poolId: string;
}): ActivityEntry[] {
  const entries: ActivityEntry[] = input.eliminated.map((e) => ({
    leagueId: input.leagueId,
    userId: e.userId,
    activityType: 'survivor_out' as const,
    message: `${e.username} went out of ${input.poolName} on ${e.teamAbbr}`,
    season: input.season,
    week: input.week,
    dedupKey: `survivor_out:${input.poolId}:${e.userId}`,
  }));

  if (input.winner) {
    entries.push({
      leagueId: input.leagueId,
      userId: input.winner.userId,
      activityType: 'survivor_won',
      message: `${input.winner.username} is the last one standing in ${input.poolName}`,
      season: input.season,
      week: input.week,
      dedupKey: `survivor_won:${input.poolId}`,
    });
  }

  return entries;
}
