-- Channels, messages and shared bets.
--
-- The feed was a read-only ledger of generated events. This turns it into
-- somewhere people actually talk: league channels with text, images and GIFs,
-- direct messages between friends, and bet slips shared from a sportsbook.
--
-- Three things are worth explaining before the DDL.
--
-- 1. Membership is modelled twice on purpose. A league channel is readable by
--    anyone in the league, so there is no row to create when somebody joins —
--    `channel_members` exists only for direct messages, where the participant
--    list IS the access rule. `channel_reads` is separate again, because unread
--    state is per-person on every channel including the implicit ones.
--
-- 2. A DM has a `dm_key`: the two user ids sorted and joined. Without it, two
--    people opening a conversation at the same moment create two conversations
--    and each sees half the messages. The key is generated by a trigger from
--    the members, not supplied by the client.
--
-- 3. Uploads are not writable by users. The bucket is public to read so an
--    <img> works without a signed URL round trip, and every write goes through
--    the API route with the service role, which is the only place file type and
--    size are checked. A browser-side upload policy would move that check to
--    somewhere a client can skip.

-- Enums ----------------------------------------------------------------------

do $$
begin
  if not exists (select 1 from pg_type where typname = 'channel_kind') then
    create type channel_kind as enum ('league', 'mode', 'dm');
  end if;
  if not exists (select 1 from pg_type where typname = 'message_kind') then
    create type message_kind as enum ('text', 'image', 'bet_slip', 'system');
  end if;
  if not exists (select 1 from pg_type where typname = 'bet_stance') then
    create type bet_stance as enum ('tail', 'fade');
  end if;
end
$$;

-- Channels -------------------------------------------------------------------

create table if not exists public.channels (
  id uuid primary key default gen_random_uuid(),
  kind channel_kind not null default 'league',
  league_id uuid references public.leagues (id) on delete cascade,
  -- Set when the channel belongs to a game mode, so a mode page can open its
  -- own room: 'pickem', 'survivor', 'td', 'h2h', 'playground'.
  mode text,
  name text not null,
  topic text,
  emoji text,
  dm_key text unique,
  is_default boolean not null default false,
  position integer not null default 0,
  created_by uuid references public.profiles (user_id) on delete set null,
  last_message_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint channels_name_len check (char_length(name) between 1 and 40),
  constraint channels_topic_len check (topic is null or char_length(topic) <= 200),
  -- A league or mode channel must name its league; a DM must not.
  constraint channels_league_scope check (
    (kind = 'dm' and league_id is null and dm_key is not null)
    or (kind <> 'dm' and league_id is not null and dm_key is null)
  ),
  constraint channels_mode_scope check ((kind = 'mode') = (mode is not null))
);

create index if not exists channels_league_idx on public.channels (league_id, position);
create index if not exists channels_recent_idx on public.channels (last_message_at desc nulls last);
create unique index if not exists channels_one_per_mode_idx
  on public.channels (league_id, mode) where mode is not null;

create trigger channels_touch before update on public.channels
  for each row execute function public.touch_updated_at();

create table if not exists public.channel_members (
  channel_id uuid not null references public.channels (id) on delete cascade,
  user_id uuid not null references public.profiles (user_id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (channel_id, user_id)
);

create index if not exists channel_members_user_idx on public.channel_members (user_id);

create table if not exists public.channel_reads (
  channel_id uuid not null references public.channels (id) on delete cascade,
  user_id uuid not null references public.profiles (user_id) on delete cascade,
  last_read_at timestamptz not null default now(),
  primary key (channel_id, user_id)
);

create index if not exists channel_reads_user_idx on public.channel_reads (user_id);

-- Shared bets ----------------------------------------------------------------

create table if not exists public.shared_bets (
  id uuid primary key default gen_random_uuid(),
  league_id uuid references public.leagues (id) on delete cascade,
  user_id uuid not null references public.profiles (user_id) on delete cascade,
  book text not null,
  -- Denormalised so a slip still renders if a leg's game is later deleted.
  legs jsonb not null default '[]'::jsonb,
  american_odds integer not null,
  stake numeric(10, 2),
  note text,
  result pick_result not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint shared_bets_book_len check (char_length(book) between 1 and 40),
  constraint shared_bets_note_len check (note is null or char_length(note) <= 280),
  constraint shared_bets_odds_range check (american_odds <= -100 or american_odds >= 100),
  constraint shared_bets_stake_range check (stake is null or (stake >= 0 and stake <= 1000000)),
  constraint shared_bets_legs_shape check (
    jsonb_typeof(legs) = 'array' and jsonb_array_length(legs) between 1 and 12
  )
);

create index if not exists shared_bets_league_idx on public.shared_bets (league_id, created_at desc);
create index if not exists shared_bets_user_idx on public.shared_bets (user_id, created_at desc);

create trigger shared_bets_touch before update on public.shared_bets
  for each row execute function public.touch_updated_at();

create table if not exists public.bet_tails (
  bet_id uuid not null references public.shared_bets (id) on delete cascade,
  user_id uuid not null references public.profiles (user_id) on delete cascade,
  stance bet_stance not null,
  created_at timestamptz not null default now(),
  primary key (bet_id, user_id)
);

create index if not exists bet_tails_bet_idx on public.bet_tails (bet_id);

-- Messages -------------------------------------------------------------------

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  channel_id uuid not null references public.channels (id) on delete cascade,
  user_id uuid references public.profiles (user_id) on delete set null,
  kind message_kind not null default 'text',
  body text,
  attachment_url text,
  attachment_type text,
  attachment_width integer,
  attachment_height integer,
  bet_id uuid references public.shared_bets (id) on delete cascade,
  reply_to_id uuid references public.messages (id) on delete set null,
  edited_at timestamptz,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),

  constraint messages_body_len check (body is null or char_length(body) between 1 and 2000),
  -- Every kind has to carry its own payload, or the client renders an empty row.
  constraint messages_payload check (
    deleted_at is not null
    or (kind = 'text' and body is not null)
    or (kind = 'image' and attachment_url is not null)
    or (kind = 'bet_slip' and bet_id is not null)
    or kind = 'system'
  ),
  constraint messages_attachment_dims check (
    (attachment_width is null or attachment_width between 1 and 20000)
    and (attachment_height is null or attachment_height between 1 and 20000)
  ),
  constraint messages_no_self_reply check (reply_to_id is null or reply_to_id <> id)
);

create index if not exists messages_channel_idx on public.messages (channel_id, created_at desc);
create index if not exists messages_user_idx on public.messages (user_id, created_at desc);
create index if not exists messages_bet_idx on public.messages (bet_id) where bet_id is not null;

create table if not exists public.message_reactions (
  message_id uuid not null references public.messages (id) on delete cascade,
  user_id uuid not null references public.profiles (user_id) on delete cascade,
  emoji text not null,
  created_at timestamptz not null default now(),
  primary key (message_id, user_id, emoji),
  constraint message_reactions_emoji_len check (char_length(emoji) between 1 and 16)
);

create index if not exists message_reactions_message_idx on public.message_reactions (message_id);

-- Opening a room ------------------------------------------------------------
--
-- Both of these are SECURITY DEFINER and both exist for the same reason: the
-- channel row and the rows that give access to it have to appear together.
--
-- A DM cannot be inserted by a client at all. `channels_league_scope` requires
-- dm_key, dm_key is derived from the participants, and the participants live in
-- a second table — so a client-side insert would either fail the constraint or
-- leave a conversation nobody can read. Routing it through a function also
-- makes the race harmless: two people tapping "message" at the same instant
-- collide on the dm_key unique index and both get the same conversation.

create or replace function public.open_dm(other_user uuid)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  me uuid := auth.uid();
  key text;
  existing uuid;
  created uuid;
begin
  if me is null then
    raise exception 'not signed in';
  end if;
  if other_user is null or other_user = me then
    raise exception 'pick somebody else';
  end if;
  if not exists (select 1 from public.profiles p where p.user_id = other_user) then
    raise exception 'no such person';
  end if;

  key := array_to_string(array(select unnest(array[me, other_user]) order by 1), ':');

  select id into existing from public.channels where dm_key = key;
  if existing is not null then
    -- Rejoin a conversation someone left, rather than starting a second one.
    insert into public.channel_members (channel_id, user_id)
    values (existing, me), (existing, other_user)
    on conflict do nothing;
    return existing;
  end if;

  insert into public.channels (kind, name, dm_key, created_by)
  values ('dm', 'Direct message', key, me)
  on conflict (dm_key) do nothing
  returning id into created;

  if created is null then
    select id into created from public.channels where dm_key = key;
  end if;

  insert into public.channel_members (channel_id, user_id)
  values (created, me), (created, other_user)
  on conflict do nothing;

  return created;
end
$$;

revoke all on function public.open_dm(uuid) from public;
grant execute on function public.open_dm(uuid) to authenticated;

-- A mode's room is created the first time somebody opens it, so a league does
-- not start life with five empty channels it never uses.

create or replace function public.ensure_mode_channel(target_league uuid, target_mode text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  existing uuid;
  created uuid;
  label text;
  mark text;
begin
  if not public.is_league_member(target_league) then
    raise exception 'not a member of that league';
  end if;

  select id into existing
  from public.channels
  where league_id = target_league and mode = target_mode;
  if existing is not null then
    return existing;
  end if;

  select l, e into label, mark from (
    values
      ('pickem', 'pickem', '🎯'),
      ('survivor', 'survivor', '🛡️'),
      ('td', 'td-scorer', '🏈'),
      ('h2h', 'head-to-head', '⚔️'),
      ('playground', 'playground', '🎲')
  ) as m(k, l, e)
  where m.k = target_mode;

  if label is null then
    raise exception 'unknown mode %', target_mode;
  end if;

  insert into public.channels (kind, league_id, mode, name, topic, emoji, position, created_by)
  values ('mode', target_league, target_mode, label, 'Talk about this mode.', mark, 10, auth.uid())
  on conflict (league_id, mode) do nothing
  returning id into created;

  if created is null then
    select id into created from public.channels
    where league_id = target_league and mode = target_mode;
  end if;

  return created;
end
$$;

revoke all on function public.ensure_mode_channel(uuid, text) from public;
grant execute on function public.ensure_mode_channel(uuid, text) to authenticated;

-- A channel's shape is fixed once created -----------------------------------

create or replace function public.enforce_channel_identity()
returns trigger
language plpgsql
as $$
begin
  if new.kind <> old.kind then
    raise exception 'a channel cannot change kind';
  end if;
  if new.league_id is distinct from old.league_id then
    raise exception 'a channel cannot move between leagues';
  end if;
  if new.dm_key is distinct from old.dm_key and old.dm_key is not null then
    raise exception 'a direct message cannot change participants';
  end if;
  return new;
end
$$;

drop trigger if exists channels_identity on public.channels;
create trigger channels_identity before update on public.channels
  for each row execute function public.enforce_channel_identity();

-- A message's provenance is fixed once sent ----------------------------------
--
-- Editing is allowed, and says so with edited_at. What is not allowed is
-- moving a message to another channel, reassigning its author, or swapping the
-- bet slip under a post people already tailed.

create or replace function public.enforce_message_immutability()
returns trigger
language plpgsql
as $$
begin
  if new.channel_id <> old.channel_id then
    raise exception 'a message cannot move between channels';
  end if;
  if new.user_id is distinct from old.user_id then
    raise exception 'a message cannot change author';
  end if;
  if new.kind <> old.kind then
    raise exception 'a message cannot change kind';
  end if;
  if new.bet_id is distinct from old.bet_id then
    raise exception 'a message cannot change which bet it shares';
  end if;
  if new.attachment_url is distinct from old.attachment_url and new.deleted_at is null then
    raise exception 'a message cannot change its attachment';
  end if;
  if new.created_at <> old.created_at then
    raise exception 'a message cannot change when it was sent';
  end if;
  if old.deleted_at is not null and new.deleted_at is null then
    raise exception 'a deleted message cannot be restored';
  end if;
  return new;
end
$$;

drop trigger if exists messages_immutable on public.messages;
create trigger messages_immutable before update on public.messages
  for each row execute function public.enforce_message_immutability();

-- Keep the channel's recency current, so the list can sort by activity -------

create or replace function public.touch_channel_activity()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.channels
  set last_message_at = new.created_at
  where id = new.channel_id
    and (last_message_at is null or last_message_at < new.created_at);
  return new;
end
$$;

drop trigger if exists messages_touch_channel on public.messages;
create trigger messages_touch_channel after insert on public.messages
  for each row execute function public.touch_channel_activity();

-- Access ---------------------------------------------------------------------

create or replace function public.can_access_channel(target_channel uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.channels c
    where c.id = target_channel
      and (
        case
          when c.kind = 'dm' then exists (
            select 1 from public.channel_members m
            where m.channel_id = c.id and m.user_id = auth.uid()
          )
          else public.is_league_member(c.league_id)
        end
      )
  );
$$;

alter table public.channels enable row level security;
alter table public.channel_members enable row level security;
alter table public.channel_reads enable row level security;
alter table public.messages enable row level security;
alter table public.message_reactions enable row level security;
alter table public.shared_bets enable row level security;
alter table public.bet_tails enable row level security;

drop policy if exists channels_read on public.channels;
create policy channels_read on public.channels
  for select using (public.can_access_channel(id) or public.is_admin());

-- Anyone in the league can open a channel. Deleting or renaming one is the
-- commissioner's call, which is why there is no general update policy.
drop policy if exists channels_insert_member on public.channels;
create policy channels_insert_member on public.channels
  for insert with check (
    created_by = auth.uid()
    and kind = 'league'
    and public.is_league_member(league_id)
  );

drop policy if exists channels_update_commissioner on public.channels;
create policy channels_update_commissioner on public.channels
  for update using (
    kind <> 'dm' and public.is_league_commissioner(league_id)
  ) with check (
    kind <> 'dm' and public.is_league_commissioner(league_id)
  );

drop policy if exists channels_delete_commissioner on public.channels;
create policy channels_delete_commissioner on public.channels
  for delete using (
    kind <> 'dm' and not is_default and public.is_league_commissioner(league_id)
  );

drop policy if exists channel_members_read on public.channel_members;
create policy channel_members_read on public.channel_members
  for select using (user_id = auth.uid() or public.can_access_channel(channel_id));

drop policy if exists channel_members_insert on public.channel_members;
create policy channel_members_insert on public.channel_members
  for insert with check (
    exists (
      select 1 from public.channels c
      where c.id = channel_id and c.created_by = auth.uid()
    )
    or user_id = auth.uid()
  );

drop policy if exists channel_members_delete_self on public.channel_members;
create policy channel_members_delete_self on public.channel_members
  for delete using (user_id = auth.uid());

drop policy if exists channel_reads_own on public.channel_reads;
create policy channel_reads_own on public.channel_reads
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists messages_read on public.messages;
create policy messages_read on public.messages
  for select using (public.can_access_channel(channel_id) or public.is_admin());

drop policy if exists messages_insert_self on public.messages;
create policy messages_insert_self on public.messages
  for insert with check (
    user_id = auth.uid()
    and kind <> 'system'
    and deleted_at is null
    and edited_at is null
    and public.can_access_channel(channel_id)
  );

drop policy if exists messages_update_author on public.messages;
create policy messages_update_author on public.messages
  for update using (user_id = auth.uid()) with check (user_id = auth.uid());

-- A commissioner can clear something out of their league's channel; everyone
-- else can only remove their own. Deletion is soft, through deleted_at, so the
-- update policies above are what matter — this covers a hard delete.
drop policy if exists messages_delete on public.messages;
create policy messages_delete on public.messages
  for delete using (
    user_id = auth.uid()
    or exists (
      select 1 from public.channels c
      where c.id = messages.channel_id
        and c.league_id is not null
        and public.is_league_commissioner(c.league_id)
    )
  );

drop policy if exists message_reactions_read on public.message_reactions;
create policy message_reactions_read on public.message_reactions
  for select using (
    exists (
      select 1 from public.messages m
      where m.id = message_reactions.message_id and public.can_access_channel(m.channel_id)
    )
  );

drop policy if exists message_reactions_write_self on public.message_reactions;
create policy message_reactions_write_self on public.message_reactions
  for all using (user_id = auth.uid()) with check (
    user_id = auth.uid()
    and exists (
      select 1 from public.messages m
      where m.id = message_reactions.message_id and public.can_access_channel(m.channel_id)
    )
  );

drop policy if exists shared_bets_read on public.shared_bets;
create policy shared_bets_read on public.shared_bets
  for select using (
    user_id = auth.uid()
    or (league_id is not null and public.is_league_member(league_id))
    or public.is_admin()
  );

drop policy if exists shared_bets_insert_self on public.shared_bets;
create policy shared_bets_insert_self on public.shared_bets
  for insert with check (
    user_id = auth.uid()
    and (league_id is null or public.is_league_member(league_id))
  );

drop policy if exists shared_bets_update_self on public.shared_bets;
create policy shared_bets_update_self on public.shared_bets
  for update using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists shared_bets_delete_self on public.shared_bets;
create policy shared_bets_delete_self on public.shared_bets
  for delete using (user_id = auth.uid());

drop policy if exists bet_tails_read on public.bet_tails;
create policy bet_tails_read on public.bet_tails
  for select using (
    exists (
      select 1 from public.shared_bets b
      where b.id = bet_tails.bet_id
        and (b.user_id = auth.uid() or (b.league_id is not null and public.is_league_member(b.league_id)))
    )
  );

drop policy if exists bet_tails_write_self on public.bet_tails;
create policy bet_tails_write_self on public.bet_tails
  for all using (user_id = auth.uid()) with check (
    user_id = auth.uid()
    and exists (
      select 1 from public.shared_bets b
      where b.id = bet_tails.bet_id
        and (b.user_id = auth.uid() or (b.league_id is not null and public.is_league_member(b.league_id)))
    )
  );

-- Every league gets a channel without anyone having to make one --------------

create or replace function public.seed_league_channels()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.channels (kind, league_id, name, topic, emoji, is_default, position, created_by)
  values
    ('league', new.id, 'general', 'Everything else.', '💬', true, 0, new.commissioner_id),
    ('league', new.id, 'trash-talk', 'Say it to their face.', '🔥', false, 1, new.commissioner_id)
  on conflict do nothing;
  return new;
end
$$;

drop trigger if exists leagues_seed_channels on public.leagues;
create trigger leagues_seed_channels after insert on public.leagues
  for each row execute function public.seed_league_channels();

-- Backfill for leagues that already exist.
insert into public.channels (kind, league_id, name, topic, emoji, is_default, position, created_by)
select 'league', l.id, 'general', 'Everything else.', '💬', true, 0, l.commissioner_id
from public.leagues l
where not exists (
  select 1 from public.channels c where c.league_id = l.id and c.name = 'general'
);

insert into public.channels (kind, league_id, name, topic, emoji, is_default, position, created_by)
select 'league', l.id, 'trash-talk', 'Say it to their face.', '🔥', false, 1, l.commissioner_id
from public.leagues l
where not exists (
  select 1 from public.channels c where c.league_id = l.id and c.name = 'trash-talk'
);

-- One pot per mode -----------------------------------------------------------
--
-- A pot was league-wide, which made it a page of its own and meant survivor and
-- pick'em shared one buy-in. `competition_type` was always on the table; this
-- makes it the identity, so each mode carries its own.

do $$
declare
  duplicates integer;
begin
  select count(*) into duplicates from (
    select league_id, season, competition_type
    from public.pots
    where league_id is not null
    group by league_id, season, competition_type
    having count(*) > 1
  ) d;

  if duplicates > 0 then
    raise exception
      'cannot make pots unique per mode: % league/season/mode combinations have more than one pot. Merge them first.',
      duplicates;
  end if;
end
$$;

create unique index if not exists pots_one_per_mode_idx
  on public.pots (league_id, season, competition_type)
  where league_id is not null;

-- Realtime -------------------------------------------------------------------
--
-- Chat is the one place polling would be obvious, so messages and reactions go
-- out over the realtime publication. RLS still applies to the stream.

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'messages'
    ) then
      alter publication supabase_realtime add table public.messages;
    end if;
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'message_reactions'
    ) then
      alter publication supabase_realtime add table public.message_reactions;
    end if;
  end if;
end
$$;

-- Attachments ----------------------------------------------------------------
--
-- Public read, no client write. See the note at the top of this file.

do $$
begin
  insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
  values (
    'chat-media',
    'chat-media',
    true,
    8388608,
    array['image/png', 'image/jpeg', 'image/webp', 'image/gif']
  )
  on conflict (id) do update
  set public = true,
      file_size_limit = 8388608,
      allowed_mime_types = array['image/png', 'image/jpeg', 'image/webp', 'image/gif'];

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage' and tablename = 'objects' and policyname = 'chat_media_public_read'
  ) then
    create policy chat_media_public_read on storage.objects
      for select using (bucket_id = 'chat-media');
  end if;
exception
  when insufficient_privilege then
    -- storage.objects belongs to supabase_storage_admin on some projects. The
    -- bucket is then created from the dashboard; uploads still work, because
    -- they go through the API route with the service role either way.
    raise warning 'could not configure the chat-media bucket from SQL: %. Create it in the Supabase dashboard as a public bucket.', sqlerrm;
end
$$;

-- Column grants, same reasoning as migration 0009: a client that can update a
-- message row must not be able to rewrite who sent it or what it attached.
revoke update on public.messages from authenticated;
grant update (body, edited_at, deleted_at) on public.messages to authenticated;
